services:
  postgres:
    image: postgres:16
    container_name: train-db
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  migrate:
    image: migrate/migrate:v4.16.2
    container_name: train-migrate
    command: ["-path", "/migrations", "-database", "postgres://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}?sslmode=disable", "up"]
    env_file:
      - ./.env
    volumes:
      - ./db/migrations:/migrations
    depends_on:
      - postgres 

  app:
    build: .
    container_name: app
    depends_on:
      - postgres
      - migrate
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  postgres-data:
