CREATE TYPE "TRAIN_STATUS" AS ENUM (
	'в депо',
	'в пути',
	'отменён',
	'задерживается',
	'прибыл',
	'ушёл',
	'закончил'
);

CREATE TYPE "REPAIR_TYPE" AS ENUM (
	'плановый',
	'рейсовый'
);

CREATE TYPE "TICKET_STATUS" AS ENUM (
	'забронирован',
	'куплен',
	'свободен',
	'возвращён'
);

CREATE TYPE "TRAIN_TYPE" AS ENUM (
	'скорый',
	'пригородный',
	'пассажирский',
	'грузовой'
);

CREATE TYPE "LOCOMOTIVE_STATUS" AS ENUM (
	'списан',
	'работает',
	'в резерве'
);

CREATE TABLE "Departments" (
	"department_id" SERIAL NOT NULL,
	"department_name" VARCHAR(255) NOT NULL UNIQUE,
	"director_id" INTEGER NOT NULL,
	PRIMARY KEY("department_id")
);

CREATE TABLE "Employees" (
	"id" SERIAL NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"surname" VARCHAR(255) NOT NULL,
	"patronymic" VARCHAR(255),
	"birth_date" DATE NOT NULL,
	"child_number" INTEGER NOT NULL,
	"hired_at" DATE NOT NULL,
	"sex" CHAR(1) NOT NULL CHECK(sex IN ('M', 'F')),
	"position_id" INTEGER NOT NULL,
	"salary" NUMERIC(10,2) NOT NULL,
	PRIMARY KEY("id")
);


CREATE TABLE "Brigades" (
	"brigade_id" SERIAL NOT NULL,
	"department_id" INTEGER NOT NULL,
	PRIMARY KEY("brigade_id")
);

CREATE TABLE "BrigadeMembers" (
	"brigade_id" INTEGER,
	"employee_id" INTEGER,
	PRIMARY KEY("brigade_id", "employee_id")
);

CREATE TABLE "Locomotives" (
	"id" SERIAL NOT NULL,
	"model" VARCHAR(255) NOT NULL,
	"status" "LOCOMOTIVE_STATUS" NOT NULL,
	"locomotive_brigade_id" INTEGER NOT NULL,
	"technic_brigade_id" INTEGER NOT NULL,
	"put_into_service" DATE,
	"base_station_id" INTEGER,
	PRIMARY KEY("id")
);

CREATE TABLE "Positions" (
	"position_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"department_id" INTEGER NOT NULL,
	"position_name" VARCHAR(255) NOT NULL,
	PRIMARY KEY("position_id")
);

CREATE TABLE "TechnicBrigades" (
	"technic_brigade_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"brigade_id" INTEGER NOT NULL,
	PRIMARY KEY("technic_brigade_id")
);

CREATE TABLE "MedicalCheckups" (
	"medical_checkup_id" INTEGER NOT NULL,
	"employee_id" INTEGER NOT NULL,
	"medical_checkup_date" DATE NOT NULL,
	PRIMARY KEY("medical_checkup_id")
);

CREATE TABLE "Trains" (
	"train_number" VARCHAR(255) NOT NULL,
	"locomotive_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"train_type" VARCHAR(255) NOT NULL,
	PRIMARY KEY("train_number")
);

CREATE TABLE "Repairs" (
	"repair_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"locomotive_id" INTEGER NOT NULL,
	"repair_start_date" DATE NOT NULL,
	"repair_end_date" DATE,
	"repair_type" "REPAIR_TYPE" NOT NULL,
	PRIMARY KEY("repair_id")
);

CREATE TABLE "Routes" (
	"route_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"train_number" VARCHAR(255) NOT NULL,
	"start_time" TIMESTAMP NOT NULL,
	"end_time" TIMESTAMP NOT NULL,
	"real_arrival_time" TIMESTAMP,
	"real_departure_time" TIMESTAMP,
	"status" "TRAIN_STATUS",
	PRIMARY KEY("route_id")
);

CREATE TABLE "DelayReason" (
	"route_id" INTEGER NOT NULL UNIQUE,
	"reason" TEXT NOT NULL,
	PRIMARY KEY("route_id")
);

CREATE TABLE "Tickets" (
	"ticket_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"route_id" INTEGER NOT NULL,
	"ticket_status" "TICKET_STATUS" NOT NULL,
	"passenger_id" INTEGER NOT NULL,
	"bought_at" TIMESTAMP,
	"price" DECIMAL NOT NULL,
	PRIMARY KEY("ticket_id")
);

CREATE TABLE "RoutesStations" (
	"route_id" INTEGER NOT NULL,
	"station_id" INTEGER NOT NULL,
	"arrival_time_id" INTEGER NOT NULL,
	"station_number" INTEGER NOT NULL,
	PRIMARY KEY("route_id", "station_id")
);

CREATE TABLE "Stations" (
	"station_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"station_name" VARCHAR(255) NOT NULL,
	"is_abroad" BOOLEAN NOT NULL,
	PRIMARY KEY("station_id")
);

CREATE TABLE "Passengers" (
	"passenger_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"surname" VARCHAR(255) NOT NULL,
	"patronimic" VARCHAR(255),
	"sex" CHAR(1) NOT NULL,
	"birth_date" DATE NOT NULL,
	PRIMARY KEY("passenger_id")
);

CREATE TABLE "Luggage" (
	"luggage_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"weight" DECIMAL,
	PRIMARY KEY("luggage_id")
);

CREATE TABLE "TicketsLuggage" (
	"ticket_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"luggage_id" INTEGER NOT NULL,
	PRIMARY KEY("ticket_id", "luggage_id")
);

CREATE TABLE "PositionsAttributesName" (
	"position_id" INTEGER NOT NULL,
	"attribute_id" INTEGER NOT NULL,
	PRIMARY KEY("position_id", "attribute_id")
);

CREATE TABLE "AttributesName" (
	"attributeName_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	PRIMARY KEY("attributeName_id")
);

CREATE TABLE "AttributesValues" (
	"attributeValue_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"attributeName_id" INTEGER NOT NULL,
	"value" TEXT NOT NULL,
	"employe_id" INTEGER NOT NULL,
	PRIMARY KEY("attributeValue_id")
);

CREATE TABLE "ArrivalTime" (
	"arrival_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"real_arrival_time" TIMESTAMP,
	"real_departure_time" TIMESTAMP,
	PRIMARY KEY("arrival_id")
);

ALTER TABLE "BrigadeMembers"
ADD FOREIGN KEY("employee_id") REFERENCES "Employees"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Locomotives"
ADD FOREIGN KEY("id") REFERENCES "Trains"("locomotive_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Repairs"
ADD FOREIGN KEY("locomotive_id") REFERENCES "Locomotives"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "RoutesStations"
ADD FOREIGN KEY("route_id") REFERENCES "Routes"("route_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "RoutesStations"
ADD FOREIGN KEY("station_id") REFERENCES "Stations"("station_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Tickets"
ADD FOREIGN KEY("route_id") REFERENCES "Routes"("route_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Routes"
ADD FOREIGN KEY("train_number") REFERENCES "Trains"("train_number")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Tickets"
ADD FOREIGN KEY("passenger_id") REFERENCES "Passengers"("passenger_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Tickets"
ADD FOREIGN KEY("ticket_id") REFERENCES "TicketsLuggage"("ticket_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "TicketsLuggage"
ADD FOREIGN KEY("luggage_id") REFERENCES "Luggage"("luggage_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Locomotives"
ADD FOREIGN KEY("locomotive_brigade_id") REFERENCES "Brigades"("brigade_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Departments"
ADD FOREIGN KEY("department_id") REFERENCES "Positions"("position_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Brigades"
ADD FOREIGN KEY("department_id") REFERENCES "Departments"("department_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "PositionsAttributesName"
ADD CONSTRAINT fk_position FOREIGN KEY("position_id") REFERENCES "Positions"("position_id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "PositionsAttributesName"
ADD CONSTRAINT fk_attribute FOREIGN KEY("attribute_id") REFERENCES "AttributesName"("attributeName_id")
ON UPDATE NO ACTION ON DELETE CASCADE;


ALTER TABLE "Departments"
ADD FOREIGN KEY("director_id") REFERENCES "Employees"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Employees"
ADD FOREIGN KEY("position_id") REFERENCES "Positions"("position_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "MedicalCheckups"
ADD FOREIGN KEY("employee_id") REFERENCES "Employees"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "AttributesValues"
ADD FOREIGN KEY("employe_id") REFERENCES "Employees"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "AttributesValues"
ADD FOREIGN KEY("attributeName_id") REFERENCES "AttributesName"("attributeName_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "BrigadeMembers"
ADD FOREIGN KEY("brigade_id") REFERENCES "Brigades"("brigade_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "TechnicBrigades"
ADD FOREIGN KEY("brigade_id") REFERENCES "Brigades"("brigade_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Locomotives"
ADD FOREIGN KEY("technic_brigade_id") REFERENCES "TechnicBrigades"("technic_brigade_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "DelayReason"
ADD CONSTRAINT fk_cancelreason_route FOREIGN KEY ("route_id") REFERENCES "Routes"("route_id")
ON UPDATE NO ACTION ON DELETE CASCADE;


ALTER TABLE "RoutesStations"
ADD FOREIGN KEY("arrival_time_id") REFERENCES "ArrivalTime"("arrival_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
